defmodule JidoManagedAgents.Repo.Migrations.AddSessionFoundationResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workspaces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :backend, :text, null: false, default: "memory_vfs"
      add :config, :map, null: false, default: %{}
      add :state, :text, null: false, default: "ready"
      add :last_used_at, :utc_datetime_usec
      add :metadata, :map, null: false, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "workspaces_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :agent_id,
          references(:agents,
            column: :id,
            name: "workspaces_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:workspaces, [:user_id, :agent_id],
             name: "workspaces_unique_workspace_per_user_agent_index"
           )

    create table(:sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text
      add :status, :text, null: false, default: "idle"
      add :stop_reason, :map
      add :last_processed_event_index, :bigint, null: false, default: -1
      add :archived_at, :utc_datetime_usec
      add :deleted_at, :utc_datetime_usec
      add :metadata, :map, null: false, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "sessions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :agent_id,
          references(:agents,
            column: :id,
            name: "sessions_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :agent_version_id,
          references(:agent_versions,
            column: :id,
            name: "sessions_agent_version_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :environment_id,
          references(:environments,
            column: :id,
            name: "sessions_environment_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "sessions_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:sessions, [:workspace_id],
             where: "deleted_at IS NULL AND status IN ('idle', 'running')",
             name: "sessions_active_workspace_idx"
           )

    create table(:session_vaults, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false, default: 0
      add :metadata, :map, null: false, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "session_vaults_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :session_id,
          references(:sessions,
            column: :id,
            name: "session_vaults_session_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :vault_id,
          references(:vaults,
            column: :id,
            name: "session_vaults_vault_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:session_vaults, [:session_id, :vault_id],
             name: "session_vaults_unique_vault_idx"
           )

    create unique_index(:session_vaults, [:session_id, :position],
             name: "session_vaults_unique_pos_idx"
           )

    create table(:session_threads, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "primary"
      add :status, :text, null: false, default: "idle"
      add :stop_reason, :map
      add :metadata, :map, null: false, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "session_threads_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :session_id,
          references(:sessions,
            column: :id,
            name: "session_threads_session_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :agent_id,
          references(:agents,
            column: :id,
            name: "session_threads_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :agent_version_id,
          references(:agent_versions,
            column: :id,
            name: "session_threads_agent_version_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :parent_thread_id,
          references(:session_threads,
            column: :id,
            name: "session_threads_parent_thread_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:session_threads, [:session_id],
             where: "role = 'primary'",
             name: "session_threads_unique_primary_idx"
           )

    create table(:session_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sequence, :bigint, null: false, default: 0
      add :type, :text, null: false
      add :content, {:array, :map}, null: false, default: []
      add :payload, :map, null: false, default: %{}
      add :processed_at, :utc_datetime_usec
      add :stop_reason, :map
      add :metadata, :map, null: false, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "session_events_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :session_id,
          references(:sessions,
            column: :id,
            name: "session_events_session_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :session_thread_id,
          references(:session_threads,
            column: :id,
            name: "session_events_session_thread_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:session_events, [:session_id, :sequence],
             name: "session_events_unique_sequence_idx"
           )
  end

  def down do
    drop_if_exists unique_index(:session_events, [:session_id, :sequence],
                     name: "session_events_unique_sequence_idx"
                   )

    drop constraint(:session_events, "session_events_user_id_fkey")
    drop constraint(:session_events, "session_events_session_id_fkey")
    drop constraint(:session_events, "session_events_session_thread_id_fkey")

    drop table(:session_events)

    drop_if_exists unique_index(:session_threads, [:session_id],
                     where: "role = 'primary'",
                     name: "session_threads_unique_primary_idx"
                   )

    drop constraint(:session_threads, "session_threads_user_id_fkey")
    drop constraint(:session_threads, "session_threads_session_id_fkey")
    drop constraint(:session_threads, "session_threads_agent_id_fkey")
    drop constraint(:session_threads, "session_threads_agent_version_id_fkey")
    drop constraint(:session_threads, "session_threads_parent_thread_id_fkey")

    drop table(:session_threads)

    drop_if_exists unique_index(:session_vaults, [:session_id, :position],
                     name: "session_vaults_unique_pos_idx"
                   )

    drop_if_exists unique_index(:session_vaults, [:session_id, :vault_id],
                     name: "session_vaults_unique_vault_idx"
                   )

    drop constraint(:session_vaults, "session_vaults_user_id_fkey")
    drop constraint(:session_vaults, "session_vaults_session_id_fkey")
    drop constraint(:session_vaults, "session_vaults_vault_id_fkey")

    drop table(:session_vaults)

    drop_if_exists unique_index(:sessions, [:workspace_id],
                     where: "deleted_at IS NULL AND status IN ('idle', 'running')",
                     name: "sessions_active_workspace_idx"
                   )

    drop constraint(:sessions, "sessions_user_id_fkey")
    drop constraint(:sessions, "sessions_agent_id_fkey")
    drop constraint(:sessions, "sessions_agent_version_id_fkey")
    drop constraint(:sessions, "sessions_environment_id_fkey")
    drop constraint(:sessions, "sessions_workspace_id_fkey")

    drop table(:sessions)

    drop_if_exists unique_index(:workspaces, [:user_id, :agent_id],
                     name: "workspaces_unique_workspace_per_user_agent_index"
                   )

    drop constraint(:workspaces, "workspaces_user_id_fkey")
    drop constraint(:workspaces, "workspaces_agent_id_fkey")

    drop table(:workspaces)
  end
end
