defmodule JidoManagedAgents.Repo.Migrations.AddCredentialFoundationResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:credentials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :mcp_server_url, :text, null: false
      add :token_endpoint, :text
      add :client_id, :text
      add :encrypted_access_token, :binary
      add :encrypted_refresh_token, :binary
      add :encrypted_client_secret, :binary
      add :metadata, :map, null: false, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :vault_id,
          references(:vaults,
            column: :id,
            name: "credentials_vault_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:credentials, [:vault_id, :type, :mcp_server_url],
             name: "credentials_unique_credential_route_per_vault_index"
           )
  end

  def down do
    drop_if_exists unique_index(:credentials, [:vault_id, :type, :mcp_server_url],
                     name: "credentials_unique_credential_route_per_vault_index"
                   )

    drop constraint(:credentials, "credentials_vault_id_fkey")

    drop table(:credentials)
  end
end
