defmodule JidoManagedAgents.Repo.Migrations.AddRoleAndApiKeyOwnerConstraints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :role, :text, null: false, default: "member"
    end

    alter table(:api_keys) do
      modify :user_id, :uuid, null: false
    end
  end

  def down do
    alter table(:api_keys) do
      modify :user_id, :uuid, null: true
    end

    alter table(:users) do
      remove :role
    end
  end
end
