defmodule JidoManagedAgents.Repo.Migrations.AddVaultFoundationResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:vaults, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :display_metadata, :map, null: false, default: %{}
      add :metadata, :map, null: false, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "vaults_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:vaults, [:user_id, :name],
             name: "vaults_unique_vault_name_per_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:vaults, [:user_id, :name],
                     name: "vaults_unique_vault_name_per_user_index"
                   )

    drop constraint(:vaults, "vaults_user_id_fkey")

    drop table(:vaults)
  end
end
