defmodule JidoManagedAgents.Repo.Migrations.AddAgentCatalogResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:skills, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false, default: "custom"
      add :name, :text, null: false
      add :description, :text
      add :metadata, :map, null: false, default: %{}
      add :archived_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "skills_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:skills, [:user_id, :name],
             name: "skills_unique_skill_name_per_user_index"
           )

    create table(:skill_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version, :bigint, null: false
      add :description, :text, null: false
      add :body, :text
      add :source_path, :text
      add :allowed_tools, {:array, :text}, null: false, default: []
      add :manifest, :map, null: false, default: %{}
      add :metadata, :map, null: false, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "skill_versions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :skill_id,
          references(:skills,
            column: :id,
            name: "skill_versions_skill_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:skill_versions, [:skill_id, :version],
             name: "skill_versions_unique_skill_version_number_index"
           )

    create table(:environments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :config, :map, null: false, default: %{}
      add :metadata, :map, null: false, default: %{}
      add :archived_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "environments_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:environments, [:user_id, :name],
             name: "environments_unique_environment_name_per_user_index"
           )

    create table(:agents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :metadata, :map, null: false, default: %{}
      add :archived_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "agents_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:agents, [:user_id, :name],
             name: "agents_unique_agent_name_per_user_index"
           )

    create table(:agent_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version, :bigint, null: false
      add :name, :text, null: false
      add :description, :text
      add :model, :map, null: false, default: %{}
      add :system, :text
      add :tools, {:array, :map}, null: false, default: []
      add :mcp_servers, {:array, :map}, null: false, default: []
      add :metadata, :map, null: false, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "agent_versions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :agent_id,
          references(:agents,
            column: :id,
            name: "agent_versions_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:agent_versions, [:agent_id, :version],
             name: "agent_versions_unique_agent_version_number_index"
           )

    create table(:agent_version_skills, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false, default: 0
      add :metadata, :map, null: false, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "agent_version_skills_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :agent_version_id,
          references(:agent_versions,
            column: :id,
            name: "agent_version_skills_agent_version_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :skill_id,
          references(:skills,
            column: :id,
            name: "agent_version_skills_skill_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :skill_version_id,
          references(:skill_versions,
            column: :id,
            name: "agent_version_skills_skill_version_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:agent_version_skills, [:agent_version_id, :skill_id],
             name: "avs_unique_skill_idx"
           )

    create unique_index(:agent_version_skills, [:agent_version_id, :position],
             name: "avs_unique_pos_idx"
           )

    create table(:agent_version_callable_agents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false, default: 0
      add :metadata, :map, null: false, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "agent_version_callable_agents_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :agent_version_id,
          references(:agent_versions,
            column: :id,
            name: "agent_version_callable_agents_agent_version_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :callable_agent_id,
          references(:agents,
            column: :id,
            name: "agent_version_callable_agents_callable_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :callable_agent_version_id,
          references(:agent_versions,
            column: :id,
            name: "agent_version_callable_agents_callable_agent_version_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:agent_version_callable_agents, [:agent_version_id, :callable_agent_id],
             name: "avca_unique_callable_idx"
           )

    create unique_index(:agent_version_callable_agents, [:agent_version_id, :position],
             name: "avca_unique_pos_idx"
           )
  end

  def down do
    drop_if_exists unique_index(:agent_version_callable_agents, [:agent_version_id, :position],
                     name: "avca_unique_pos_idx"
                   )

    drop_if_exists unique_index(
                     :agent_version_callable_agents,
                     [:agent_version_id, :callable_agent_id],
                     name: "avca_unique_callable_idx"
                   )

    drop constraint(:agent_version_callable_agents, "agent_version_callable_agents_user_id_fkey")

    drop constraint(
           :agent_version_callable_agents,
           "agent_version_callable_agents_agent_version_id_fkey"
         )

    drop constraint(
           :agent_version_callable_agents,
           "agent_version_callable_agents_callable_agent_id_fkey"
         )

    drop constraint(
           :agent_version_callable_agents,
           "agent_version_callable_agents_callable_agent_version_id_fkey"
         )

    drop table(:agent_version_callable_agents)

    drop_if_exists unique_index(:agent_version_skills, [:agent_version_id, :position],
                     name: "avs_unique_pos_idx"
                   )

    drop_if_exists unique_index(:agent_version_skills, [:agent_version_id, :skill_id],
                     name: "avs_unique_skill_idx"
                   )

    drop constraint(:agent_version_skills, "agent_version_skills_user_id_fkey")

    drop constraint(:agent_version_skills, "agent_version_skills_agent_version_id_fkey")

    drop constraint(:agent_version_skills, "agent_version_skills_skill_id_fkey")

    drop constraint(:agent_version_skills, "agent_version_skills_skill_version_id_fkey")

    drop table(:agent_version_skills)

    drop_if_exists unique_index(:agent_versions, [:agent_id, :version],
                     name: "agent_versions_unique_agent_version_number_index"
                   )

    drop constraint(:agent_versions, "agent_versions_user_id_fkey")

    drop constraint(:agent_versions, "agent_versions_agent_id_fkey")

    drop table(:agent_versions)

    drop_if_exists unique_index(:agents, [:user_id, :name],
                     name: "agents_unique_agent_name_per_user_index"
                   )

    drop constraint(:agents, "agents_user_id_fkey")

    drop table(:agents)

    drop_if_exists unique_index(:environments, [:user_id, :name],
                     name: "environments_unique_environment_name_per_user_index"
                   )

    drop constraint(:environments, "environments_user_id_fkey")

    drop table(:environments)

    drop_if_exists unique_index(:skill_versions, [:skill_id, :version],
                     name: "skill_versions_unique_skill_version_number_index"
                   )

    drop constraint(:skill_versions, "skill_versions_user_id_fkey")

    drop constraint(:skill_versions, "skill_versions_skill_id_fkey")

    drop table(:skill_versions)

    drop_if_exists unique_index(:skills, [:user_id, :name],
                     name: "skills_unique_skill_name_per_user_index"
                   )

    drop constraint(:skills, "skills_user_id_fkey")

    drop table(:skills)
  end
end
